// GENERATED by scripts/gen-embedded-sqlite.mjs — DO NOT EDIT BY HAND.
//
// A vanilla, extension-capable SQLite for the darwin standalone binaries. bun:sqlite uses Apple's
// system SQLite on macOS, which is built WITHOUT extension support, so db.loadExtension() — and
// therefore all of dense retrieval — cannot work there without this. See db/bun-sqlite.ts for the
// setCustomSQLite() call that consumes it, and this script's header for the full rationale.
//
// PER-BUILD artifact, not source: publish.yml regenerates this for each darwin --compile target
// immediately before compiling, and never commits the result. The value in git is the empty
// placeholder below; every non-darwin target and every non-compiled path keeps it, and the adapter
// treats empty as "nothing to do".
//
// Regenerate with `node scripts/gen-embedded-sqlite.mjs --target <bun-darwin-x64|bun-darwin-arm64>`.

/** Base64-encoded universal2 libsqlite3.dylib (x86_64 + arm64), extension-capable.
 *  Empty in source control; only ever non-empty inside a compiled darwin release binary. */
export const EMBEDDED_SQLITE_BASE64 = "";
