// GENERATED by scripts/gen-embedded-vec.mjs — DO NOT EDIT BY HAND.
//
// THE-663: the sibling vec.ts resolves sqlite-vec via node_modules, which breaks under
// `bun build --compile` (import.meta.url freezes to the build machine's path — see vec.ts's
// loadVec() for the fallback that reads EMBEDDED_VEC_BASE64 below). Full rationale in this
// script's header.
//
// This is a PER-TARGET build artifact, not source: publish.yml's build-binaries job regenerates
// this file once per bun --compile target (there are 5, one per platform sqlite-vec publishes),
// immediately before compiling, and never commits the result. The value checked into git is the
// empty placeholder below — every other path (`bun run`, the npm dist build, every test suite)
// never touches it, because loadVec() tries the npm require() first and only falls back here on
// failure, which outside a --compile binary never happens.
//
// Regenerate with `bun run vec:embed -- --target <bun-target>`.

/** Base64-encoded sqlite-vec `vec0` shared library for the target this binary was compiled for.
 *  Empty in source control; only ever non-empty inside a compiled release binary. */
export const EMBEDDED_VEC_BASE64 = "";
