// WP8 (post-refactor-program follow-up): notes-tools.ts (1,042 lines) was never one of the six
// WP1-WP6 extraction targets — it surfaced only after that program finished, as the new largest
// production source file. This is the invariant every one of those six extractions proved first
// and never touched again: the ordered public metadata of the 11 M1 note tools
// (read_note, read_notes, list_notes, note_exists, write_note, append_note, patch_note,
// delete_note, move_note, copy_note — the actual `buildNotesTools` array order, not the domain
// prose order) — name, description, domain, requiredScopes, tags, whether the tool declares a
// `pathAcl` extractor, the destructive flag, and the top-level keys of its input/output schema.
// None of that is allowed to move while the file underneath it is split into packages/server/src/
// tools/m1/notes/*.
//
// Deliberately an inline expected constant, NOT `toMatchSnapshot()`: there is no `__snapshots__`
// directory under packages/server/test, so an auto-written snapshot would be created-and-pass on
// the very first run, proving nothing. An inline literal has to be edited on purpose.
//
// Both snapshot and expectation are run through a stable (key-sorted) JSON serializer before
// comparison, so a key-order accident in either the code under test or this file can never produce
// a false pass. EXPECTED below was generated by invoking buildNotesTools against the pre-split
// notes-tools.ts and is otherwise unedited.
import { describe, expect, it } from "vitest";
import { buildNotesTools } from "../src/tools/m1/notes-tools";
import { VaultRegistry } from "../src/vault/registry";
import { topLevelShape } from "./schema-introspect";

interface ToolSnapshot {
  name: string;
  description: string;
  domain: string | undefined;
  requiredScopes: string[];
  tags: string[];
  hasPathAcl: boolean;
  destructive: boolean;
  inputKeys: string[];
  outputKeys: string[];
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(record[k])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function toSnapshot(tool: ReturnType<typeof buildNotesTools>[number]): ToolSnapshot {
  const inputShape = topLevelShape(tool.inputSchema) ?? {};
  const outputShape = topLevelShape(tool.outputSchema) ?? {};
  return {
    name: tool.name,
    description: tool.description,
    domain: tool.domain,
    requiredScopes: [...tool.requiredScopes].sort(),
    tags: [...(tool.tags ?? [])].sort(),
    hasPathAcl: tool.pathAcl !== undefined,
    destructive: tool.destructive ?? false,
    inputKeys: Object.keys(inputShape).sort(),
    outputKeys: Object.keys(outputShape).sort(),
  };
}

const EXPECTED: ToolSnapshot[] = [
  {
    name: "read_note",
    description:
      "Read a note's raw content, parsed frontmatter, body, content hash, and stat. With anchor (same shape as patch_note's: a heading section, a block reference, or the frontmatter preamble), also returns section: the resolved span's text (including its heading/block-id marker line), 1-based start_line/end_line relative to the raw file, and heading_level for a heading anchor. content_hash stays the whole-note hash so it round-trips into patch_note's prev_hash unchanged. response_format=concise returns {vault, path, body, content_hash}: the note body without its frontmatter block (and, with an anchor, the section instead of the whole body).",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["anchor", "path", "response_format", "vault", "verbosity"],
    outputKeys: [
      "body",
      "content",
      "content_hash",
      "frontmatter",
      "has_frontmatter",
      "path",
      "section",
      "stat",
      "vault",
    ],
  },
  {
    name: "read_notes",
    description:
      "Batch-read notes. Returns successful notes and a per-path error list (partial). The response is held under the server's byte budget: when the batch does not fit, the notes that fit are returned with next_cursor; call again with the same arguments plus cursor to continue exactly where the page stopped (request order, no duplicates, no gaps) until next_cursor is null. A single note too large to ever fit is reported as a too_large error (with its size and the budget) and skipped, so the walk always makes progress. A cursor is bound to the caller, the tool and these exact arguments, and expires. response_format=concise returns each note as {path, body, content_hash} (no raw content, no frontmatter); per-path errors are unchanged.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["cursor", "paths", "response_format", "vault", "verbosity"],
    outputKeys: ["errors", "next_cursor", "notes", "vault"],
  },
  {
    name: "read_resources",
    description:
      "Batch resources/read: read many obsidian-tc://<vault>/<path> note resource URIs in one call. Returns one result per URI in request order: {ok: true, uri, mimeType, text} (identical to a single resources/read) or {ok: false, uri, error} for a malformed or unsupported URI, another vault's URI, a denied or missing note. The response is held under the server's byte budget: when the batch does not fit, the results that fit are returned with next_cursor; call again with the same arguments plus cursor to continue exactly where the page stopped (request order, no duplicates, no gaps) until next_cursor is null. A single resource too large to ever fit is reported as a too_large error (with its size and the budget) and skipped, so the walk always makes progress. A cursor is bound to the caller, the tool and these exact arguments, and expires. response_format=concise returns each item as {ok: true, uri, text} with the note body only (no frontmatter block, no mimeType); error items are unchanged.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: false,
    destructive: false,
    inputKeys: ["cursor", "response_format", "uris", "verbosity"],
    outputKeys: ["next_cursor", "results"],
  },
  {
    name: "list_notes",
    description:
      "List notes under a folder (read-ACL filtered), with cursor pagination. response_format=concise returns {vault, notes: [{path}], next_cursor}, without size, mtime, folder and total_returned.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: false,
    destructive: false,
    inputKeys: [
      "cursor",
      "extensions",
      "folder",
      "limit",
      "recursive",
      "response_format",
      "vault",
      "verbosity",
    ],
    outputKeys: ["folder", "next_cursor", "notes", "total_returned", "vault"],
  },
  {
    name: "note_exists",
    description: "Check whether a path exists in the vault and whether it is a file or folder.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["path", "vault"],
    outputKeys: ["exists", "path", "type", "vault"],
  },
  {
    name: "write_note",
    description:
      'Create, overwrite, or upsert a note. Optional prev_hash gives compare-and-swap; overwriting a non-empty note requires confirmation. Set provenance: "agent_synthesis" when the content is a derived/inferred conclusion an agent produced (not directly stated in any single source) rather than authored/copied text — this routes the content through a poison scan before the write lands (rejected outright on high risk) and surfaces the assessment in the result; also add source: agent-synthesis to the note\'s own frontmatter by convention. response_format=concise acknowledges with {vault, path, content_hash} only (plus quality_warning, poison_assessment or redactions when they carry something).',
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: elicit_token is advertised for describe_capability discoverability but stripped
    // off rawArgs before this schema ever validates it (mcp/server.ts), so it changes nothing
    // about dispatch.
    inputKeys: [
      "content",
      "elicit_token",
      "mode",
      "options",
      "path",
      "prev_hash",
      "provenance",
      "response_format",
      "vault",
      "verbosity",
    ],
    outputKeys: [
      "bytes_written",
      "content_hash",
      "created",
      "mode_used",
      "path",
      "poison_assessment",
      "prev_hash",
      "quality_warning",
      "redactions",
      "vault",
    ],
  },
  {
    name: "append_note",
    description:
      'Append content to the END of a note (optionally creating it with create_if_missing: true), preserving existing bytes. It takes no anchor: to add under a specific heading, or anywhere other than the end, use patch_note instead. Set provenance: "agent_synthesis" when the appended content is a derived/inferred conclusion an agent produced rather than authored/copied text — this routes the appended content through a poison scan before the write lands (rejected outright on high risk) and surfaces the assessment in the result; also add source: agent-synthesis to the note\'s own frontmatter by convention. response_format=concise acknowledges with {vault, path, content_hash} only (plus quality_warning, poison_assessment or redactions when they carry something).',
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: [
      "content",
      "create_if_missing",
      "ensure_newline",
      "options",
      "path",
      "prev_hash",
      "provenance",
      "response_format",
      "vault",
      "verbosity",
    ],
    outputKeys: [
      "bytes_written",
      "content_hash",
      "created",
      "path",
      "poison_assessment",
      "prev_hash",
      "quality_warning",
      "redactions",
      "vault",
    ],
  },
  {
    name: "patch_note",
    description:
      'Edit part of an existing note in place. Name an anchor: a heading section (anchor:{type:"heading",heading:"Notes"}), a block reference (anchor:{type:"block",block_id}), or the preamble above the first heading (anchor:{type:"frontmatter"}); then an operation: append/prepend/replace content, or replace_text (old_string/new_string). Frontmatter is preserved. Examples: add a line to the end of a section = operation append + heading anchor + content. Move, reorder or duplicate sections = ONE replace_text anchored on an enclosing heading (the note\'s top-level H1 spans every section below it): old_string is those sections as they are now, new_string the same text rearranged; the anchor heading line itself is never touched. To add at the very end of a note use append_note, which needs no anchor. A heading that appears more than once needs anchor.occurrence (1-based, document order) or a path (heading:"Parent > Child"); without either the call is refused with every matching line number, never silently bound to the first match (same for a block id on more than one line). On a heading anchor, replace preserves the anchor heading line itself; if content\'s first non-blank line repeats it (same level and text), that line is dropped so the two calling conventions do not double the heading. replace_text takes old_string/new_string instead of content and substitutes an exact match scoped to the resolved anchor\'s section — 0 or 2+ matches is refused (with the count for 2+); confirm_replace is ignored for it. A replace on a heading anchor that would discard more than 20 lines AND over half of the note\'s body (e.g. the note\'s only H1, which no lower-or-equal heading bounds) is refused unless confirm_replace is set. Snapshots (restore_note\'s undo) are captured only when the server\'s snapshots.enabled config is on; the default "trusted-local" posture leaves it on, so such a write is rollback-able via restore_note unless snapshots have been explicitly disabled. response_format=concise acknowledges with {vault, path, content_hash} only (plus quality_warning, redactions, and lines_removed/bytes_removed when non-zero).',
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: [
      "anchor",
      "confirm_replace",
      "content",
      "new_string",
      "old_string",
      "operation",
      "path",
      "prev_hash",
      "response_format",
      "target_heading",
      "vault",
      "verbosity",
    ],
    outputKeys: [
      "anchor",
      "bytes_removed",
      "content_hash",
      "lines_removed",
      "operation",
      "path",
      "prev_hash",
      "quality_warning",
      "redactions",
      "target_heading",
      "vault",
    ],
  },
  {
    name: "delete_note",
    description:
      "Delete a note (to the vault's .trash mirror, or permanently). Destructive — requires confirmation. restore_note reads its undo from a snapshot, which is captured only when the server's snapshots.enabled config is on; the default \"trusted-local\" posture leaves it on, so a deleted note has a restore_note path back unless snapshots have been explicitly disabled.",
    domain: "notes",
    requiredScopes: ["delete:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: true,
    inputKeys: ["path", "permanent", "prev_hash", "vault"],
    outputKeys: ["deleted", "path", "permanent", "prev_hash", "trashed_to", "vault"],
  },
  {
    name: "move_note",
    description:
      "Move/rename a note and update backlinks. Crossing a folder boundary OR overwriting an existing destination requires confirmation; an overwritten destination is soft-deleted to .trash (recoverable).",
    domain: "notes",
    requiredScopes: ["delete:notes", "write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: see write_note's elicit_token comment above.
    inputKeys: [
      "elicit_token",
      "from",
      "options",
      "overwrite",
      "prev_hash",
      "to",
      "update_backlinks",
      "vault",
    ],
    outputKeys: [
      "backlinks_updated",
      "content_hash",
      "from",
      "moved",
      "overwritten",
      "to",
      "trashed_dest_to",
      "vault",
    ],
  },
  {
    name: "copy_note",
    description: "Copy a note to a new path (backlinks are not rewritten for copies).",
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: see write_note's elicit_token comment above.
    inputKeys: ["elicit_token", "from", "options", "overwrite", "to", "vault"],
    outputKeys: ["content_hash", "copied", "from", "overwritten", "to", "trashed_dest_to", "vault"],
  },
];

function stubDeps() {
  return {
    vaultRegistry: new VaultRegistry([{ id: "main", name: "main", path: "/tmp/does-not-exist" }]),
    version: "test",
    startedAt: 0,
    embeddings: { provider: "stub", model: "stub" },
  };
}

describe("m1 notes tool metadata parity (WP8 invariant)", () => {
  it("keeps the ordered public metadata of the 11 M1 note tools byte-identical", () => {
    const tools = buildNotesTools(stubDeps(), () => undefined);
    const actual = tools.map(toSnapshot);
    expect(stableStringify(actual)).toBe(stableStringify(EXPECTED));
  });
});
