// WP8 (post-refactor-program follow-up): notes-tools.ts (1,042 lines) was never one of the six
// WP1-WP6 extraction targets — it surfaced only after that program finished, as the new largest
// production source file. This is the invariant every one of those six extractions proved first
// and never touched again: the ordered public metadata of the 10 M1 note-CRUD tools
// (read_note, read_notes, list_notes, note_exists, write_note, append_note, patch_note,
// delete_note, move_note, copy_note — the actual `buildNotesTools` array order, not the domain
// prose order) — name, description, domain, requiredScopes, tags, whether the tool declares a
// `pathAcl` extractor, the destructive flag, and the top-level keys of its input/output schema.
// None of that is allowed to move while the file underneath it is split into packages/server/src/
// tools/m1/notes/*.
//
// Deliberately an inline expected constant, NOT `toMatchSnapshot()`: there is no `__snapshots__`
// directory under packages/server/test, so an auto-written snapshot would be created-and-pass on
// the very first run, proving nothing. An inline literal has to be edited on purpose.
//
// Both snapshot and expectation are run through a stable (key-sorted) JSON serializer before
// comparison, so a key-order accident in either the code under test or this file can never produce
// a false pass. EXPECTED below was generated by invoking buildNotesTools against the pre-split
// notes-tools.ts and is otherwise unedited.
import { describe, expect, it } from "vitest";
import { buildNotesTools } from "../src/tools/m1/notes-tools";
import { VaultRegistry } from "../src/vault/registry";
import { topLevelShape } from "./schema-introspect";

interface ToolSnapshot {
  name: string;
  description: string;
  domain: string | undefined;
  requiredScopes: string[];
  tags: string[];
  hasPathAcl: boolean;
  destructive: boolean;
  inputKeys: string[];
  outputKeys: string[];
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort();
    return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(record[k])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function toSnapshot(tool: ReturnType<typeof buildNotesTools>[number]): ToolSnapshot {
  const inputShape = topLevelShape(tool.inputSchema) ?? {};
  const outputShape = topLevelShape(tool.outputSchema) ?? {};
  return {
    name: tool.name,
    description: tool.description,
    domain: tool.domain,
    requiredScopes: [...tool.requiredScopes].sort(),
    tags: [...(tool.tags ?? [])].sort(),
    hasPathAcl: tool.pathAcl !== undefined,
    destructive: tool.destructive ?? false,
    inputKeys: Object.keys(inputShape).sort(),
    outputKeys: Object.keys(outputShape).sort(),
  };
}

const EXPECTED: ToolSnapshot[] = [
  {
    name: "read_note",
    description: "Read a note's raw content, parsed frontmatter, body, content hash, and stat.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["path", "vault"],
    outputKeys: [
      "body",
      "content",
      "content_hash",
      "frontmatter",
      "has_frontmatter",
      "path",
      "stat",
      "vault",
    ],
  },
  {
    name: "read_notes",
    description: "Batch-read notes. Returns successful notes and a per-path error list (partial).",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["paths", "vault"],
    outputKeys: ["errors", "notes", "vault"],
  },
  {
    name: "list_notes",
    description: "List notes under a folder (read-ACL filtered), with cursor pagination.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: false,
    destructive: false,
    inputKeys: ["cursor", "extensions", "folder", "limit", "recursive", "vault"],
    outputKeys: ["folder", "next_cursor", "notes", "total_returned", "vault"],
  },
  {
    name: "note_exists",
    description: "Check whether a path exists in the vault and whether it is a file or folder.",
    domain: "notes",
    requiredScopes: ["read:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: ["path", "vault"],
    outputKeys: ["exists", "path", "type", "vault"],
  },
  {
    name: "write_note",
    description:
      "Create, overwrite, or upsert a note. Optional prev_hash gives compare-and-swap; overwriting a non-empty note requires confirmation.",
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: elicit_token is advertised for describe_capability discoverability but stripped
    // off rawArgs before this schema ever validates it (mcp/server.ts), so it changes nothing
    // about dispatch.
    inputKeys: ["content", "elicit_token", "mode", "options", "path", "prev_hash", "vault"],
    outputKeys: [
      "bytes_written",
      "content_hash",
      "created",
      "mode_used",
      "path",
      "prev_hash",
      "quality_warning",
      "vault",
    ],
  },
  {
    name: "append_note",
    description: "Append content to a note (optionally creating it), preserving existing bytes.",
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: [
      "content",
      "create_if_missing",
      "ensure_newline",
      "options",
      "path",
      "prev_hash",
      "vault",
    ],
    outputKeys: [
      "bytes_written",
      "content_hash",
      "created",
      "path",
      "prev_hash",
      "quality_warning",
      "vault",
    ],
  },
  {
    name: "patch_note",
    description:
      'Insert or replace content (append/prepend/replace) relative to an anchor: a heading section, a block reference (anchor:{type:"block",block_id}), or the note preamble above the first heading (anchor:{type:"frontmatter"}). Frontmatter is preserved. A replace on a heading anchor that would discard more than 20 lines AND over half of the note\'s body (e.g. the note\'s only H1, which no lower-or-equal heading bounds) is refused unless confirm_replace is set. Snapshots (restore_note\'s undo) are captured only when the server\'s snapshots.enabled config is on; the default "trusted-local" posture leaves it on, so such a write is rollback-able via restore_note unless snapshots have been explicitly disabled.',
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    inputKeys: [
      "anchor",
      "confirm_replace",
      "content",
      "operation",
      "path",
      "prev_hash",
      "target_heading",
      "vault",
    ],
    outputKeys: [
      "anchor",
      "bytes_removed",
      "content_hash",
      "lines_removed",
      "operation",
      "path",
      "prev_hash",
      "quality_warning",
      "target_heading",
      "vault",
    ],
  },
  {
    name: "delete_note",
    description:
      "Delete a note (to the vault's .trash mirror, or permanently). Destructive — requires confirmation. restore_note reads its undo from a snapshot, which is captured only when the server's snapshots.enabled config is on; the default \"trusted-local\" posture leaves it on, so a deleted note has a restore_note path back unless snapshots have been explicitly disabled.",
    domain: "notes",
    requiredScopes: ["delete:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: true,
    inputKeys: ["path", "permanent", "prev_hash", "vault"],
    outputKeys: ["deleted", "path", "permanent", "prev_hash", "trashed_to", "vault"],
  },
  {
    name: "move_note",
    description:
      "Move/rename a note and update backlinks. Crossing a folder boundary OR overwriting an existing destination requires confirmation; an overwritten destination is soft-deleted to .trash (recoverable).",
    domain: "notes",
    requiredScopes: ["delete:notes", "write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: see write_note's elicit_token comment above.
    inputKeys: [
      "elicit_token",
      "from",
      "options",
      "overwrite",
      "prev_hash",
      "to",
      "update_backlinks",
      "vault",
    ],
    outputKeys: [
      "backlinks_updated",
      "content_hash",
      "from",
      "moved",
      "overwritten",
      "to",
      "trashed_dest_to",
      "vault",
    ],
  },
  {
    name: "copy_note",
    description: "Copy a note to a new path (backlinks are not rewritten for copies).",
    domain: "notes",
    requiredScopes: ["write:notes"],
    tags: [],
    hasPathAcl: true,
    destructive: false,
    // THE-824: see write_note's elicit_token comment above.
    inputKeys: ["elicit_token", "from", "options", "overwrite", "to", "vault"],
    outputKeys: ["content_hash", "copied", "from", "overwritten", "to", "trashed_dest_to", "vault"],
  },
];

function stubDeps() {
  return {
    vaultRegistry: new VaultRegistry([{ id: "main", name: "main", path: "/tmp/does-not-exist" }]),
    version: "test",
    startedAt: 0,
    embeddings: { provider: "stub", model: "stub" },
  };
}

describe("m1 notes tool metadata parity (WP8 invariant)", () => {
  it("keeps the ordered public metadata of the 10 M1 note-CRUD tools byte-identical", () => {
    const tools = buildNotesTools(stubDeps());
    const actual = tools.map(toSnapshot);
    expect(stableStringify(actual)).toBe(stableStringify(EXPECTED));
  });
});
