// GH #1027: the decision record for `response_format`. Every registered tool is exactly one of
//   1. response_format-aware (its input schema advertises the parameter; derived live, not listed),
//   2. EXEMPT_FROM_RESPONSE_FORMAT: reviewed, and concise would drop nothing a caller can spare,
//   3. NOT_YET_COVERED_BY_RESPONSE_FORMAT: not reviewed yet, so still detailed-only.
// response-format-coverage.test.ts enforces the partition, so a new tool cannot skip the decision.
// Moving a tool from list 3 to "aware" means deleting its name here, nothing else.
//
// The exempt reasons are mirrored in the "Response format" section of the user docs.

export const EXEMPT_FROM_RESPONSE_FORMAT: Readonly<Record<string, string>> = {
  list_tags: "one {tag, count} row per tag: already minimal",
  list_properties: "one {key, type, count} row per property: already minimal",
  list_vaults: "one minimal row per vault: nothing to drop",
  list_workspaces: "a list of workspace names only: nothing to drop",
  list_kanban_boards: "one minimal row per board: nothing to drop",
  list_bookmarks: "the items tree and the CAS content_hash are the payload",
  list_commands: "opaque plugin passthrough, {id, name} per command",
  list_quickadd_actions: "opaque plugin passthrough, {name, type} per action",
  list_templates: "opaque plugin passthrough, {path, name} per template",
  list_tasks: "every field is task data; optional fields are already omitted when empty",
  list_contradictions: "the rationale is the product",
  episode_stats: "aggregate counts only",
  find_orphans: "bare paths already",
  plur_get: "read-only proxy of an external payload we do not own",
  plur_recall: "read-only proxy of an external payload we do not own",
  plur_recall_hybrid: "read-only proxy of an external payload we do not own",
  plur_similarity_search: "read-only proxy of an external payload we do not own",
};

/** Reviewed in no part of #1027 yet. Each part of the series shrinks this list; none grows it
 *  except a newly registered tool that has not been decided. */
export const NOT_YET_COVERED_BY_RESPONSE_FORMAT: readonly string[] = [
  // git bridge
  "git_commit",
  "git_diff",
  "git_log",
  "git_stage",
  "git_status",
  // bases, canvas, excalidraw, kanban, tables, dataview and plugin readers
  "create_base",
  "create_canvas",
  "create_excalidraw",
  "add_kanban_card",
  "move_kanban_card",
  "read_base",
  "read_canvas",
  "read_excalidraw",
  "read_kanban_board",
  "query_base",
  "query_canvas",
  "update_base",
  "update_canvas",
  "update_excalidraw",
  "format_table",
  "insert_table_column",
  "insert_table_row",
  "sort_table_by_column",
  "eval_dataview_field",
  "search_dql",
  "validate_dql",
  "query_datacore",
  "makemd_list_spaces",
  "makemd_query",
  "search_omnisearch",
  "remotely_save_status",
  "remotely_save_trigger",
  // bundles and OCR
  "bundle_files",
  "bundle_folder",
  "ocr_attachment",
  "ocr_bulk",
  // knowledge reads and analysis
  "audit_provenance",
  "diagnose_retrieval",
  "explain_answer",
  "knowledge_challenge",
  "knowledge_get_critical",
  "reflect",
  "vault_context",
  "vault_health_score",
  "suggest_links",
  "suggest_tags",
  "get_link_strength",
  "find_link_cycles",
  "graph_centrality",
  "graph_communities",
  "graph_path_between",
  // memory, goal, session and episode writes and acks
  "add_observation",
  "close_goal",
  "commit_capture",
  "create_entity",
  "delete_entity",
  "end_session",
  "enqueue_capture",
  "link_entities",
  "record_retrieval_feedback",
  "rename_entity",
  "session_rerun",
  "set_goal",
  "start_session",
  "unlink_entities",
  "work_forget",
  "work_result",
  // note, attachment, tag, property and snapshot operations
  "add_tag",
  "remove_tag",
  "bulk_create_notes",
  "bulk_move_notes",
  "bulk_set_property",
  "copy_note",
  "delete_note",
  "move_note",
  "note_exists",
  "restore_note",
  "snapshot_note",
  "read_snapshot",
  "find_notes_by_tag",
  "get_note_tags",
  "read_property",
  "read_metadata_fields",
  "delete_active_file",
  "delete_attachment",
  "get_attachment",
  "move_attachment",
  "write_attachment",
  // bookmarks, workspaces, periodic notes, templates, tasks and other plugin actions
  "add_bookmark",
  "remove_bookmark",
  "open_workspace",
  "save_workspace",
  "append_to_periodic_note",
  "create_periodic_note",
  "find_or_create_periodic_note",
  "get_periodic_note",
  "resolve_daily_note",
  "execute_command",
  "execute_template",
  "trigger_quickadd",
  "tasks_filter",
  "update_task",
  "generate_uri",
  "show_file_in_obsidian",
  // vault registry, index and server administration
  "add_vault",
  "get_vault",
  "index_vault",
  "reload_vault",
  "reset_vault_cache",
  "refresh_plugin_capabilities",
  "get_index_status",
  "get_metrics",
  "get_server_config",
  "inspect_acl",
  "inspect_visibility",
  "server_health",
];
