#!/usr/bin/env bun
// Emit a JSON Schema for obsidian-tc.config.json from the Zod schema that already validates it.
//
// WHY THIS IS WORTH DOING AND WHY IT IS CHEAP. The config surface is the customization layer for
// anyone who does not want to write code — toolVisibility, auth.mode, acl, retrieval, embeddings —
// and it is currently undiscoverable: you have to read TypeScript to find out a key exists. The
// descriptions are ALREADY written (187 `.describe()` calls across config.schema.ts); they were
// just never emitted anywhere an editor could read them. Publishing the JSON Schema turns them
// into inline docs and autocomplete in VS Code and every other editor that speaks `$schema`.
//
// Generated, never hand-maintained: the Zod schema stays the single source of truth, so a new key
// with a `.describe()` shows up in the editor automatically. --check makes drift a CI failure
// rather than something discovered when the published schema is already stale.
//
// usage:
//   bun scripts/gen-config-schema.ts            # write docs/obsidian-tc.config.schema.json
//   bun scripts/gen-config-schema.ts --check    # fail if the committed file is stale
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "obsidian-tc.config.schema.json");

// Drift is checked two ways, and neither is a pinned literal (a single shared hash made any two
// config PRs conflict by construction):
//   1. STALENESS — the regenerated bytes must equal the committed file.
//   2. STRUCTURE vs the base branch (`--base <ref>`): every key whose type, default or constraint
//      changed, or that was removed, must be named by `config-schema-change:` in the change's
//      release-note fragment (changes/<slug>.md). Added keys and reworded descriptions need nothing.
//      Regenerating the schema can therefore never hide an unintended change to an existing key.
// `--base` without a resolvable ref FAILS (fail closed); without `--base` the structural half is
// reported as NOT RUN, never as passed. CI passes `--base origin/main`.

// The CONVERSION lives in packages/shared (configJsonSchema), not here. A script under scripts/
// resolves its imports from its own directory upward, so importing `zod` here only works when the
// workspace happens to hoist it to the root — true locally, false on the CI runner. Importing the
// shared module by absolute path works either way, and it is the module that owns the schema.
const { configJsonSchema } = await import(
  join(ROOT, "packages", "shared", "src", "config.schema.ts")
);

const schema = configJsonSchema();
schema.$schema = "https://json-schema.org/draft/2020-12/schema";
schema.title = "obsidian-tc server config";
schema.description =
  'Configuration for obsidian-tc. Generated from packages/shared/src/config.schema.ts — do not edit by hand. Add `"$schema": "./obsidian-tc.config.schema.json"` to your config for editor autocomplete.';

const json = `${JSON.stringify(schema, null, 2)}\n`;

// A schema that documented nothing would still be valid JSON and would still pass a naive
// "file exists" check, so assert the descriptions actually survived the conversion. This is the
// only property that makes the artifact worth publishing at all.
const described = (JSON.stringify(schema).match(/"description":/g) ?? []).length;
if (described < 100)
  throw new Error(
    `only ${described} descriptions survived into the JSON Schema; config.schema.ts carries ~187 .describe() calls, so the conversion dropped them and the artifact would be useless`,
  );

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error(`config schema missing: ${OUT}\nRun: bun scripts/gen-config-schema.ts`);
    process.exit(1);
  }
  if (current !== json) {
    console.error(
      `config schema is STALE: ${OUT}\nThe Zod schema changed without regenerating.\nRun: bun scripts/gen-config-schema.ts`,
    );
    process.exit(1);
  }

  const baseIdx = process.argv.indexOf("--base");
  const baseRef = baseIdx === -1 ? undefined : process.argv[baseIdx + 1];
  if (baseIdx !== -1 && !baseRef) {
    console.error("config schema: --base needs a git ref (e.g. --base origin/main)");
    process.exit(1);
  }
  let structure = "structure vs base NOT RUN (pass --base <ref>; CI passes --base origin/main)";
  if (baseRef) {
    let baseJson: string;
    try {
      baseJson = execFileSync("git", ["show", `${baseRef}:docs/obsidian-tc.config.schema.json`], {
        cwd: ROOT,
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
        stdio: ["ignore", "pipe", "pipe"],
      });
    } catch (err) {
      // Fail closed: a check that cannot read its baseline has compared nothing.
      console.error(
        `config schema: cannot read docs/obsidian-tc.config.schema.json at "${baseRef}" ` +
          `(${(err as Error).message.split("\n")[0]}). Fetch the ref, or drop --base.`,
      );
      process.exit(1);
    }
    const { diffStructure, flattenSchema, unacknowledged } = await import(
      join(ROOT, "scripts", "lib", "config-schema-structure.mjs")
    );
    const { readFragments } = await import(join(ROOT, "scripts", "lib", "changes.mjs"));
    const base = flattenSchema(JSON.parse(baseJson));
    const head = flattenSchema(schema);
    // Floor: an empty flattening means the walk broke, not that nothing changed.
    if (base.size < 100 || head.size < 100) {
      console.error(
        `config schema: structural walk saw ${base.size}/${head.size} nodes (floor 100)`,
      );
      process.exit(1);
    }
    const diff = diffStructure(base, head);
    const acknowledged = readFragments(ROOT).flatMap(
      (f: { schemaChange: string[] }) => f.schemaChange,
    );
    const bad = unacknowledged(diff, acknowledged);
    if (bad.length > 0) {
      console.error(
        `config schema: ${bad.length} existing key(s) changed type/default/constraint or were removed vs ${baseRef} without acknowledgement:\n` +
          bad.map((b: { path: string; kind: string }) => `  ${b.kind}: ${b.path}`).join("\n") +
          "\nIf deliberate, add `config-schema-change: <key>[, <key>]` to the front matter of this change's " +
          "changes/<slug>.md release-note fragment. If not, the refactor altered the published schema by accident.",
      );
      process.exit(1);
    }
    structure = `structure vs ${baseRef}: +${diff.added.length} added, ${diff.changed.length} changed, ${diff.removed.length} removed, all acknowledged`;
  }
  console.log(`config schema OK (${described} descriptions, up to date; ${structure})`);
} else {
  writeFileSync(OUT, json);
  console.log(`wrote ${OUT} (${described} descriptions)`);
}
